### ISSUE TITLE
live stream of Youtube

### ISSUE THREAD

**Issue by ATavanaei** [iBicha/youtube-dl-server#10]
Is it possible to use this package for live streaming on youtube?
we have a live stream on youtube son if it's possible to use this package for the stream live URL?

**Comment by iBicha** [comment]
Yes, if you pass a video id of a live stream, you will get an `index.m3u8` file back.
That link can be read from supported video players (vlc for example, or Safari browser - Chrome seems to download the file instead of playing it as a live stream).

You can test this by opening this for example URL https://unity-youtube-dl-server.herokuapp.com/watch?v=jfKfPfyJRdk&cli=yt-dlp (until that stream ends)

Hope this helps
